name: deploy-docs

on:
  push:
  workflow_run:
    workflows: ["upload-javadoc"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check if docs were modified
        id: check_files
        run: |
          echo "::set-output name=run_job::false"
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == web/* ]]; then
              echo "Docs have been modified, run deployment"
              echo "::set-output name=run_job::true"
              break
            fi
          done < files.txt
  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.run_job == 'true'
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build docs
        run: yarn run build
      - name: Commit and push changes
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          external_repository: 'ACRA/acra.github.com'
          publish_branch: 'master'
          publish_dir: ./web/build/
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          full_commit_message: "Update docs from ${{ github.ref }}"