name: upload-javadoc

on:
  push:
    tags:
      - 'acra-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Checkout acra
        uses: actions/checkout@v2
        with:
          path: 'main'
          persist-credentials: false
          fetch-depth: 0
      - name: Checkout github pages
        uses: actions/checkout@v2
        with:
          repository: 'ACRA/acra.github.com'
          path: 'web'
          persist-credentials: false
          fetch-depth: 0
      - name: Generate Javadoc
        run: ./gradlew dokkaHtmlCollector --no-daemon
        working-directory: ./main
      - name: Extract version
        id: version
        run: echo "::set-output name=value::$(./gradlew version --no-daemon --quiet --console=plain)"
        working-directory: ./main
      - name: Update Javadoc
        run: |
          mkdir ./web/javadoc/${{ steps.version.outputs.value }}
          cp -a ./main/build/dokka/htmlCollector/. ./web/javadoc/${{ steps.version.outputs.value }}/
          echo  "- [${{ steps.version.outputs.value }}](${{ steps.version.outputs.value }}/acra)" >> ./web/javadoc/index.md
          ln -sfn "${{ steps.version.outputs.value }}/" ./web/javadoc/latest
      - name: Commit and push changes
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          external_repository: 'ACRA/acra.github.com'
          publish_branch: 'master'
          publish_dir: ./web
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          full_commit_message: "Add javadoc for version ${{ steps.version.outputs.value }}"
